import {
  MapPin,
  Coffee,
  UtensilsCrossed,
  Moon,
  Palette,
  Trees,
  ShoppingBag,
  Heart,
  Compass,
  Laptop,
  Camera,
  Music,
  Dumbbell,
  BookOpen,
  Mountain,
  Beer,
  Star,
  Building,
  Bike,
  Globe,
} from "lucide-react";

export const CURATED_CATEGORY_ICONS = [
  { name: "MapPin", icon: MapPin },
  { name: "Coffee", icon: Coffee },
  { name: "UtensilsCrossed", icon: UtensilsCrossed },
  { name: "Moon", icon: Moon },
  { name: "Palette", icon: Palette },
  { name: "Trees", icon: Trees },
  { name: "ShoppingBag", icon: ShoppingBag },
  { name: "Heart", icon: Heart },
  { name: "Compass", icon: Compass },
  { name: "Laptop", icon: Laptop },
  { name: "Camera", icon: Camera },
  { name: "Music", icon: Music },
  { name: "Dumbbell", icon: Dumbbell },
  { name: "BookOpen", icon: BookOpen },
  { name: "Mountain", icon: Mountain },
  { name: "Beer", icon: Beer },
  { name: "Star", icon: Star },
  { name: "Building", icon: Building },
  { name: "Bike", icon: Bike },
  { name: "Globe", icon: Globe },
] as const;
